// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAei6RpyMoZCiNJsVYPJ2sxXqUFSj6ouAs',
    appId: '1:983836622625:web:0e5d454487d6de5cb44860',
    messagingSenderId: '983836622625',
    projectId: 'assignment-4878b',
    authDomain: 'assignment-4878b.firebaseapp.com',
    databaseURL: 'https://assignment-4878b-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-4878b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnf0OXdXSVSTAxd_fCLutF5wiKprFzsoU',
    appId: '1:983836622625:android:1974d71ed19a9a6ab44860',
    messagingSenderId: '983836622625',
    projectId: 'assignment-4878b',
    databaseURL: 'https://assignment-4878b-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-4878b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAYRXZ4GG_bxJOjwo5T6iRLlQDRYqLwY0',
    appId: '1:983836622625:ios:688958e46e02c20db44860',
    messagingSenderId: '983836622625',
    projectId: 'assignment-4878b',
    databaseURL: 'https://assignment-4878b-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-4878b.appspot.com',
    androidClientId: '983836622625-9hkvn9adiojhf9esto792gdtvd17vpbi.apps.googleusercontent.com',
    iosClientId: '983836622625-ou051gbop5377okv2et9aho1hmsuei9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAYRXZ4GG_bxJOjwo5T6iRLlQDRYqLwY0',
    appId: '1:983836622625:ios:688958e46e02c20db44860',
    messagingSenderId: '983836622625',
    projectId: 'assignment-4878b',
    databaseURL: 'https://assignment-4878b-default-rtdb.firebaseio.com',
    storageBucket: 'assignment-4878b.appspot.com',
    androidClientId: '983836622625-9hkvn9adiojhf9esto792gdtvd17vpbi.apps.googleusercontent.com',
    iosClientId: '983836622625-ou051gbop5377okv2et9aho1hmsuei9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsin',
  );
}
